import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import "./globals.css";

const ComicNew = Comic_Neue({
  weight: "700",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ComicNew.className} ${ComicNew} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
